default_language_version:
    python: python3.8
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --strict .
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest ./tests
        language: system
        pass_filenames: false